#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

export SUBLIME=subl
export VSCODE=code
export EDITOR="$VSCODE --wait"
export VISUAL=$EDITOR
export LSCOLORS="Gxfxcxdxbxegedabagacad"
export RBENV_HOME=$HOME/.rbenv
export NPM_HOME=/usr/local/share/npm
export NVM_DIR="$HOME/.nvm"
  . "/usr/local/opt/nvm/nvm.sh"
export GOPATH="$HOME/Projects/go"
export FLUTTER="$HOME/Projects/dart/flutter"
export PATH=$NPM_HOME/bin:$RBENV_HOME/bin:/usr/local/bin:/usr/local/sbin:$FLUTTER/bin:$PATH

alias l="ls -la"
alias f="find . -iname"
alias ff="find . -type f -iname"
hs() { history | grep $* }
alias ...='cd ../..'
mcd() { mkdir -p "$1" && cd "$1" }

# Confs
alias reload=". ~/.zshrc"
alias conf="$EDITOR ~/.zshrc"

alias s="subl"
alias s.="subl ."

cj() { curl -X POST -d $1 -H 'Content-type: application/json' $2 }

unsetopt CORRECT

# pip should only run if there is a virtualenv currently activated
export PIP_REQUIRE_VIRTUALENV=true
# cache pip-installed packages to avoid re-downloading
export PIP_DOWNLOAD_CACHE=$HOME/.pip/cache
gpip(){
   PIP_REQUIRE_VIRTUALENV="" pip "$@"
}

if which rbenv > /dev/null; then eval "$(rbenv init - --no-rehash)"; fi
export PATH=$HOME/bin:$PATH

autoload -Uz promptinit
promptinit
prompt steeef

# The next line updates PATH for the Google Cloud SDK.
source '/Users/patrick/google-cloud-sdk/path.zsh.inc'

# The next line enables shell command completion for gcloud.
source '/Users/patrick/google-cloud-sdk/completion.zsh.inc'

eval "$(direnv hook zsh)"
